---
- hosts: labservers
  become: yes
  var:
    rule: http
  tasks:
  - name: Include the variables from the YAML filr
    include_vars: vars/variables.yml

  - name: Include the enviornment file and set the variables
    include_vars: tasks/enviornment.yml
    vars:
      package: httpd
      service: httpd
      svc_state: started

  - name: Install the firewall
    yum:
      name: "{{ firewall_pkg }}"
      state: latest

  - name: Start the firewall
    service:
      name: firewalld
      state: started
      enabled: true

  - name: Open the port for {{ rule }}
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

  - name: Create index.html file for hosting static content
    copy:
      content: "{{ ansible_fqdn }} has been customized using Ansible on the {{ ansible_date_time.date }}\n"
      dest: /var/www/html/index.html