---
# vars file for roles/db-tier
db_pkg:
  - mariadb
  - mariadb-server
  - MySQL-python
  - firewalld
db_srv: mariadb
db:
  user: rtranch
  database: userdb
  password: rtranch
  backupfilr: userdb.backup